# tasks file for redis
---
- name: configure | init | update script
  template:
    src: etc/init.d/redis-server.j2
    dest: "/etc/init.d/{{ redis_instance_service }}"
    owner: root
    group: root
    mode: 0755
  notify: restart redis-server
  tags:
    - redis-configure-initd-update
